rm TestPrograms/test11.tig
rm TestPrograms/test12.tig
rm TestPrograms/test14.tig
rm TestPrograms/test15.tig
rm TestPrograms/test18.tig
rm TestPrograms/test19.tig
rm TestPrograms/test21.tig
rm TestPrograms/test34.tig
rm TestPrograms/test4.tig
rm TestPrograms/test44.tig
rm TestPrograms/test6.tig
rm TestPrograms/test7.tig
rm TestPrograms/test8.tig
rm TestPrograms/test9.tig